apiVersion: v1
kind: Service
metadata:
  name: cloudethix-clusterip
  labels:
    release: release_nginx
spec:
  type: ClusterIP
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

